### ISSUE TITLE
Use of CPIX for PSSH boxes with multiple keys?

### ISSUE THREAD

**Issue by mlove-au** [Axinom/cpix#1]
Hi, 

This is not so much as an issue with this repository, but a request for information as this repo appears to be one of the early adopters of the CPIX standard.  In the DRMSystem element, each element appears to be indexed by the systemId and a keyId, and the spec (v2.0) mentions that the PSSH element "is the full PSSH box that is added in the ISOBMFF". Since a single PSSH box may contain multiple key ids, does this imply that for each key id the PSSH box is duplicated into a separate DRMSystem element?  How should I handle a case where I have several keys within a single PSSH box for a single DRM system?

Thanks

**Comment by sandersaares** [comment]
Hi, Matt!

There is a CPIX issue tracker at https://github.com/Dash-Industry-Forum/CPIX/issues but it is currently marked private. I will see if I can get it opened up, so there is a nice and official place to file such issues.

To address your specific question: the contents of a PSSH box are private to the DRM system involved and CPIX makes no assumptions regarding this, treating it as opaque data.

It is perhaps helpful to think of the DRMSystem elements in terms of their reason for existence: the packager may want to know what DRM metadata to package together with encrypted tracks. For each encrypted track, it can scan the list of DRMSystem elements and find the ones with a matching key ID. Then it inserts the data from these into the content (for each DRM system associated with that key ID).

Following this workflow, you can directly observe that any PSSH you wish to insert into the content using this mechanism will need to be represented by a DRMSystem element that signals the key ID used for the particular track.

There is no concept of "PSSH sharing" in CPIX - if you want the same PSSH used with multiple keys, you need the same PSSH in multiple DRMSystem elements.

**Comment by mlove-au** [comment]
Hi Sander,

Thanks for the info. If the bug tracker could be made accessible or public it would be great!

Thanks
